apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: performance-dev-alpha-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/proxy-body-size: 20m
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "3000"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3000"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3000"
    nginx.ingress.kubernetes.io/proxy-next-upstream-timeout: "3000"
    nginx.ingress.kubernetes.io/client-header-timeout: "3000"
spec:
  tls:
  - hosts:
    - performance-dev.tbs.alpha.canada.ca
    secretName: performance-dev-tls-secret-prod
  rules:
  - host: performance-dev.tbs.alpha.canada.ca
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: performance-dev-nginx
            port:
              number: 80 