name: Deploy to AKS Cluster
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Decrypt large secret
      run: ./docker/performance-dev_php/secrets_enc/decrypt.sh
      env:
        SECRETS_PASSPHRASE: ${{ secrets.SECRETS_PASSPHRASE }}
    
    - uses: Azure/docker-login@v1
      with:
        login-server: tbsdevacr.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
    
    - run: |
        docker build -f ./docker/performance-dev_php/Dockerfile . -t tbsdevacr.azurecr.io/performance-dev_php:${{ github.sha }}
        docker push tbsdevacr.azurecr.io/performance-dev_php:${{ github.sha }}
        docker build -f ./docker/performance-dev_nginx/Dockerfile . -t tbsdevacr.azurecr.io/performance-dev_nginx:${{ github.sha }}
        docker push tbsdevacr.azurecr.io/performance-dev_nginx:${{ github.sha }}
      
    # Set the target AKS cluster.
    - uses: Azure/aks-set-context@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'
        cluster-name: tbs-prod-aks
        resource-group: tbs-prod-rg
            
    - uses: Azure/k8s-deploy@v1
      with:
        manifests: |
          kubernetes/performance-dev-php-deployment.yml
          kubernetes/performance-dev-php-service.yml
        images: |
          tbsdevacr.azurecr.io/performance-dev_php:${{ github.sha }}
        namespace: |
          performance

    - uses: Azure/k8s-deploy@v1
      with:
        manifests: |
          kubernetes/performance-dev-nginx-configmap.yml
          kubernetes/performance-dev-nginx-deployment.yml
          kubernetes/performance-dev-nginx-service.yml
        images: |
          tbsdevacr.azurecr.io/performance-dev_nginx:${{ github.sha }}
        namespace: |
          performance
